### ISSUE TITLE
User creation active user swap [2]

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#1]
When creating a new user, upon submitting the form, the current user is logged out of the system and the new user is automatically logged in. We need to fix this to not have the current user logged out so that more users can be added.

This will also be necessary in order to allow bulk adding of users.

**Comment by Jraymond** [comment]
issue fixed (as far as i can tell). possible security issue but otherwise it works as intended.

**Comment by jwroche44** [comment]
If there is a possible security issue this is not completed

**Comment by zoboso** [comment]
There probably isn't a security issue; but Josh was concerned about laravel
doing something unintended because of the fix.

**Comment by Jraymond** [comment]
I will show you Monday Jeff. there is a hidden function I cant find that is involved, there is no impact on the front-end from this fix, so as far as I'm concerned this is now a laravel issue and not something we can fix further.
