### ISSUE TITLE
Convert lightbox code [2]

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#12]
Convert the previously completed lightbox code to be source code similar to W3Schools How-To. This is simpler than using the plugin and reduces licensing liabilities.

**Comment by kelleystoll** [comment]
This is already done as per my comment on Friday.

**Comment by jwroche44** [comment]
@kelleystoll I know I was adding it in just so we can show that progress you made. What branch is this on so I can review it?

**Comment by kelleystoll** [comment]
@jwroche44 
Ah, ok sounds good. I did not update that in the excel sheet so I'll make sure it's listed as 2 tasks when I review the powerpoint on Tuesday.

It is on the branch drag_drop.

**Comment by jwroche44** [comment]
I'm going to be updating the excel sheet tonight so I'll add it in when I do that update

**Comment by kelleystoll** [comment]
Ok thanks 

Best Regards,
Kelley Stoll

**Comment by jwroche44** [comment]
This will need to be updated before merging:

- The work should be completed in the course view as this is relevant to that view
- Javascript code should be moved to an external script. Maybe make one called CourseViewScript.js and save it in public/js

I may have more comments but it's tough to run on a view that doesn't have a route to it

This is the result of a code review

**Comment by jwroche44** [comment]
I'm calling this bug closed as it will continue to be updated in the story card for the course content sectioning
