### ISSUE TITLE
Course Content Sectioning [4]

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#4]
Once upon a time in a kingdom far away, there was a User who wanted to section course content but they couldn't because it didn't exist yet. They were very sad until one day an awesome engineer came to the kingdom's rescue and made it so that the User can organize a course into sections. The engineer received a raise and everyone lived happily ever after.

**Sprint 5:**
- [x] Create the model
- [x] Create the database layout [id, course_id, order, description, visible]
-  _Add controller function to add a new section_
-  _Add controller function to remove a section_
-  _Add controller function to update a section_
-  _Add controller function to toggle if students can see a section_
- [x] Add a lightbox to the teacher course view to add a section
- [x] Add a lightbox to the teacher course view to edit a section
-  _Add a button to remove a course section for teachers_
- [x] Add a button to edit a course section for teachers (opens lightbox)
- [x] Add a button to add a course section for teachers (opens lightbox)
-  _Add a drag and drop feature for re-ordering_ 

_Technical Debt_
**Sprint 6:**
- [x] Add controller function to add a new section
- [x] Add controller function to remove a section
- [x] Add controller function to update a section
- [x] Add controller function to toggle if students can see a section
- [x] Add a button to remove a course section for teachers
- [x] Add a drag and drop feature for re-ordering

**Comment by zoboso** [comment]
The model and migration were created in my branch today

**Comment by jwroche44** [comment]
Check off what you completed please

**Comment by jwroche44** [comment]
@kelleystoll use this library if bootstrap doesn't have an adequate replacement:
http://sorgalla.com/lity/

**Comment by kelleystoll** [comment]
I added another view (wasn't sure what view to include them in) that contains the Add and Edit buttons and displays a lightbox. I wasn't too sure what to actually contain in the lightbox but the functionality is all implemented.

**Comment by jwroche44** [comment]
Kelley what you did is good for now. We will address this first in sprint 6

**Comment by kelleystoll** [comment]
Thanks for commenting on my work. See you later today and let me know if there's anything I can do to help prepare. 

Best Regards,
Kelley Stoll

**Comment by kelleystoll** [comment]
I added the drag/drop functionality. I really don't know if it counts as 1 task though because I added Jeff's preferred code to make the lightbox code simplier... but I'll put it down as one task for now.

**Comment by jwroche44** [comment]
This will need to be updated before merging:

The work should be completed in the course view as this is relevant to that view
Javascript code should be moved to an external script. Maybe make one called CourseViewScript.js and save it in public/js
I may have more comments but it's tough to run on a view that doesn't have a route to it

This is the result of a code review

**Comment by Jraymond** [comment]
almost all done. Jeff need you to look at the visible check box. the form is in but I can't find a way to make things visible/hidden without changing a lot of other things (like the database). I can do that, but if there's a shorter way it would be better to go with that.

**Comment by jwroche44** [comment]
There isn't a shorter way. Add a field to the database
