### ISSUE TITLE
Setup Unit Testing

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#7]
Setup the built in laravel unit tests for the code that is already implemented from the previous sprints.

** Everyone should be creating unit tests as they work from now on

**Comment by zoboso** [comment]
https://laravel.com/docs/5.0/testing

**Comment by jwroche44** [comment]
Don't use the above link. that's the wrong version of laravel

Here is the correct version:
https://laravel.com/docs/5.3/testing

**Comment by jwroche44** [comment]
phpunit is already installed in our installation and we are free to create new unit tests
