### ISSUE TITLE
Add a Course Catalog [5]

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#8]
Once upon a time in a kingdom far away, there was a student who wanted to a course catalog but they couldn't because it didn't exist yet. They were very sad until one day an awesome engineer came to the kingdom's rescue and made it so that the student can see what courses the school offers. The engineer received a raise and everyone lived happily ever after.

- [x] Add course types to the course db
- [x] Add course type model and migration
- [x] Add course type seeds
- [x] Create one to many relation with courses (many courses to one type) (mimic course content type)
- [ ] Allow courses to be filtered by type (CS, Math, English, etc.)
- [ ] Allow courses to be searched for
- [x] Create a new view to hold the results
- [x] List relevant courses in a new view
- [x] Allow Admins to add new types of courses
- [ ] Allow admins to remove types of courses
- [ ] Create unit tests for any controller methods created

**Comment by Jraymond** [comment]
I updated this with what is and isn't done. i could't find the view that said it was done so I unchecked it. everything else that is checked is finished as of today.

**Comment by Jraymond** [comment]
Finished create new view, list in new view, and add new types.

**Comment by Jraymond** [comment]
Jeff, we might want to think about getting rid of the "remove types" task. we are getting pretty close to the end of the line here.

**Comment by Jraymond** [comment]
the last three tasks seem like they will be a big pain in the ass. if someone else can put them in super easy go for it, but we may want to think about getting rid of them as tasks
